### ISSUE TITLE
When 6 GPUs Mining Then Application Crushed After About 10 Minutes 

### ISSUE THREAD

**Issue by mehmetalidumlu** [nanopool/ClaymoreZECMiner#10]
Hi,
Claymore is working with 5 GPUs but when increase GPU count application crush.
This message from log file: **No connection could be made because the target machine actively refused it**.

I changed Equihash to DaggerHashimato in Nicehash it works properly. But ZecMiner not works on my system.

Can anybody help me?

**Comment by ITwrx** [comment]
you might consider installing a Linux distro. Gnu/Linux won't give you any issues with gpu quantity.

**Comment by mehmetalidumlu** [comment]
@ITwrx thanks
