### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by UNIcodeX** [nanopool/ClaymoreZECMiner#3]
First of all, thanks for your awesome miner!

Now for the question. Your latest update states that a stock RX480 should do 260 H/s. I have two MSI RX480 4GB Gaming cards and they don't go above 240 - 243 H/s each, for a total of not more than 483.xx H/s. This is even when I try -asm 1,1 and -i 8 flags.

Any ideas??'

here's my miner string:
ZecMiner64.exe -zpool zec.coinmine.pl:7007 -zwal xxx.worker1 -zpsw x -tstop 90 -tt 77 -fanmin 70 -r 360 -asm 1,1

**Comment by bikkits** [comment]
try get rid of -asm and use -i 8  and/or -a 2

intensity/algorithm

**Comment by UNIcodeX** [comment]
doing that got me to 245 each. better... must be the cards i have or something else.

**Comment by UNIcodeX** [comment]
update.... I ended up using ATIWinFlash and Polaris BIOS editor to change the memory timings and that got me up to where it's supposed to be.
